#!/bin/bash
# Quick Start Script - Studio Tattoo Cyber Tribal (Astro)

echo "🎨 Studio Tattoo Cyber Tribal"
echo "🚀 Quick Start Guide"
echo ""
echo "1️⃣  PRIMEIRO USO? Instale dependências:"
echo "   npm install"
echo ""
echo "2️⃣  DESENVOLVER LOCALMENTE:"
echo "   npm run dev"
echo "   → Abre http://localhost:4321/"
echo ""
echo "3️⃣  FAZER BUILD PARA PRODUÇÃO:"
echo "   npm run build"
echo "   → Gera arquivos otimizados em /dist/"
echo ""
echo "4️⃣  TESTAR O BUILD GERADO:"
echo "   npm run preview"
echo ""
echo "📁 Estrutura do Projeto:"
echo "   src/pages/index.astro .......... Página principal"
echo "   src/styles/global.css ......... Estilos"
echo "   public/images/ ................ Imagens"
echo ""
echo "📚 Documentação:"
echo "   README.md ..................... Instruções principais"
echo "   MIGRATION_SUMMARY.md .......... Resumo da migração"
echo "   PROJECT_STRUCTURE.md ......... Estrutura detalhada"
echo "   MIGRATION_CHECKLIST.md ....... Validação visual"
echo "   PERFORMANCE_GUIDE.md ......... Otimizações futuras"
echo ""
echo "✅ Tudo já está configurado e funcionando!"
echo "🎉 Bom desenvolvimento!"
